# https://riptutorial.com/docker-compose
version: '3.1'

services:

  db:
    image: sameersbn/postgresql
    environment:
      POSTGRES_PASSWORD: example
      DB_USER: rosario
      DB_PASS: rosariopwd
      DB_NAME: rosariosis

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: rosario
      PGPASSWORD: rosariopwd
      PGDATABASE: rosariosis
      ROSARIOSIS_YEAR: 2020
#      ROSARIOSIS_LANG: 'es_ES'
