version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-rosario}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rosariopwd}
      POSTGRES_DB: ${DB_NAME:-rosariosis}

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: ${DB_USER:-rosario}
      PGPASSWORD: ${DB_PASSWORD:-rosariopwd}
      PGDATABASE: ${DB_NAME:-rosariosis}
      ROSARIOSIS_YEAR: 2022
      ROSARIOSIS_LANG: ${SIS_LANG:-'en_US'}
      ROSARIOSIS_ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.org}
